### ISSUE TITLE
Congrats!

### ISSUE THREAD

**Issue by josefdlange** [krwenholz/ssmendozawedding#1]
Pass on my congratulations. This isn't really an issue but I thought it'd be a fun way to share!

**Comment by krwenholz** [comment]
Will do! It is a fun way to share ;)   BTW, designing for mobile and regular browsers at the same time is a PITA when you're trying to do it quickly. (And when you're a barely literate CSS/HTML/JS programmer.)

**Comment by josefdlange** [comment]
Bootstrap! Use Bootstrap! It's responsive by design!
